# Generated by Django 5.2 on 2025-05-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0002_productionstage_actual_nest_sheets_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productionstage",
            name="build_status",
            field=models.CharField(
                choices=[
                    ("NOT_STARTED", "Not Started"),
                    ("IN_PROGRESS", "In Progress"),
                    ("STUCK", "Stuck"),
                    ("ON_HOLD", "On Hold"),
                    ("CANCELLED", "Cancelled"),
                    ("COMPLETED", "Completed"),
                    ("Ready", "Ready"),
                ],
                default="NOT_STARTED",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="productionstage",
            name="edge_status",
            field=models.CharField(
                choices=[
                    ("NOT_STARTED", "Not Started"),
                    ("IN_PROGRESS", "In Progress"),
                    ("STUCK", "Stuck"),
                    ("ON_HOLD", "On Hold"),
                    ("CANCELLED", "Cancelled"),
                    ("COMPLETED", "Completed"),
                    ("Ready", "Ready"),
                ],
                default="NOT_STARTED",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="productionstage",
            name="fittings_status",
            field=models.CharField(
                choices=[
                    ("NOT_STARTED", "Not Started"),
                    ("IN_PROGRESS", "In Progress"),
                    ("STUCK", "Stuck"),
                    ("ON_HOLD", "On Hold"),
                    ("CANCELLED", "Cancelled"),
                    ("COMPLETED", "Completed"),
                    ("Ready", "Ready"),
                ],
                default="NOT_STARTED",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="productionstage",
            name="nest_status",
            field=models.CharField(
                choices=[
                    ("NOT_STARTED", "Not Started"),
                    ("IN_PROGRESS", "In Progress"),
                    ("STUCK", "Stuck"),
                    ("ON_HOLD", "On Hold"),
                    ("CANCELLED", "Cancelled"),
                    ("COMPLETED", "Completed"),
                    ("Ready", "Ready"),
                ],
                default="NOT_STARTED",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="productionstage",
            name="prep_status",
            field=models.CharField(
                choices=[
                    ("NOT_STARTED", "Not Started"),
                    ("IN_PROGRESS", "In Progress"),
                    ("STUCK", "Stuck"),
                    ("ON_HOLD", "On Hold"),
                    ("CANCELLED", "Cancelled"),
                    ("COMPLETED", "Completed"),
                    ("Ready", "Ready"),
                ],
                default="NOT_STARTED",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="productionstage",
            name="programming_status",
            field=models.CharField(
                choices=[
                    ("NOT_STARTED", "Not Started"),
                    ("IN_PROGRESS", "In Progress"),
                    ("STUCK", "Stuck"),
                    ("ON_HOLD", "On Hold"),
                    ("CANCELLED", "Cancelled"),
                    ("COMPLETED", "Completed"),
                    ("Ready", "Ready"),
                ],
                default="NOT_STARTED",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="productionstage",
            name="quality_status",
            field=models.CharField(
                choices=[
                    ("NOT_STARTED", "Not Started"),
                    ("IN_PROGRESS", "In Progress"),
                    ("STUCK", "Stuck"),
                    ("ON_HOLD", "On Hold"),
                    ("CANCELLED", "Cancelled"),
                    ("COMPLETED", "Completed"),
                    ("Ready", "Ready"),
                ],
                default="NOT_STARTED",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="productionstage",
            name="wrapping_status",
            field=models.CharField(
                choices=[
                    ("NOT_STARTED", "Not Started"),
                    ("IN_PROGRESS", "In Progress"),
                    ("STUCK", "Stuck"),
                    ("ON_HOLD", "On Hold"),
                    ("CANCELLED", "Cancelled"),
                    ("COMPLETED", "Completed"),
                    ("Ready", "Ready"),
                ],
                default="NOT_STARTED",
                max_length=20,
            ),
        ),
    ]
