# Generated by Django 5.2 on 2025-04-27 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0002_alter_order_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductionStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sales_status",
                    models.CharField(
                        choices=[
                            ("NOT_STARTED", "Not Started"),
                            ("IN_PROGRESS", "In Progress"),
                            ("STUCK", "Stuck"),
                            ("ON_HOLD", "On Hold"),
                            ("CONFIRMATION", "Confirmation"),
                            ("NO_PAPERWORK", "No Paperwork"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="NOT_STARTED",
                        max_length=20,
                    ),
                ),
                (
                    "programming_status",
                    models.CharField(
                        choices=[
                            ("NOT_STARTED", "Not Started"),
                            ("IN_PROGRESS", "In Progress"),
                            ("STUCK", "Stuck"),
                            ("ON_HOLD", "On Hold"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="NOT_STARTED",
                        max_length=20,
                    ),
                ),
                (
                    "nest_status",
                    models.CharField(
                        choices=[
                            ("NOT_STARTED", "Not Started"),
                            ("IN_PROGRESS", "In Progress"),
                            ("STUCK", "Stuck"),
                            ("ON_HOLD", "On Hold"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="NOT_STARTED",
                        max_length=20,
                    ),
                ),
                (
                    "edge_status",
                    models.CharField(
                        choices=[
                            ("NOT_STARTED", "Not Started"),
                            ("IN_PROGRESS", "In Progress"),
                            ("STUCK", "Stuck"),
                            ("ON_HOLD", "On Hold"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="NOT_STARTED",
                        max_length=20,
                    ),
                ),
                (
                    "prep_status",
                    models.CharField(
                        choices=[
                            ("NOT_STARTED", "Not Started"),
                            ("IN_PROGRESS", "In Progress"),
                            ("STUCK", "Stuck"),
                            ("ON_HOLD", "On Hold"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="NOT_STARTED",
                        max_length=20,
                    ),
                ),
                (
                    "build_status",
                    models.CharField(
                        choices=[
                            ("NOT_STARTED", "Not Started"),
                            ("IN_PROGRESS", "In Progress"),
                            ("STUCK", "Stuck"),
                            ("ON_HOLD", "On Hold"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="NOT_STARTED",
                        max_length=20,
                    ),
                ),
                (
                    "fittings_status",
                    models.CharField(
                        choices=[
                            ("NOT_STARTED", "Not Started"),
                            ("IN_PROGRESS", "In Progress"),
                            ("STUCK", "Stuck"),
                            ("ON_HOLD", "On Hold"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="NOT_STARTED",
                        max_length=20,
                    ),
                ),
                (
                    "wrapping_status",
                    models.CharField(
                        choices=[
                            ("NOT_STARTED", "Not Started"),
                            ("IN_PROGRESS", "In Progress"),
                            ("STUCK", "Stuck"),
                            ("ON_HOLD", "On Hold"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="NOT_STARTED",
                        max_length=20,
                    ),
                ),
                (
                    "quality_status",
                    models.CharField(
                        choices=[
                            ("NOT_STARTED", "Not Started"),
                            ("IN_PROGRESS", "In Progress"),
                            ("STUCK", "Stuck"),
                            ("ON_HOLD", "On Hold"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="NOT_STARTED",
                        max_length=20,
                    ),
                ),
                ("sales_target_date", models.DateField(blank=True, null=True)),
                ("programming_target_date", models.DateField(blank=True, null=True)),
                ("nest_target_date", models.DateField(blank=True, null=True)),
                ("edge_target_date", models.DateField(blank=True, null=True)),
                ("prep_target_date", models.DateField(blank=True, null=True)),
                ("build_target_date", models.DateField(blank=True, null=True)),
                ("fittings_target_date", models.DateField(blank=True, null=True)),
                ("wrapping_target_date", models.DateField(blank=True, null=True)),
                ("quality_target_date", models.DateField(blank=True, null=True)),
                ("sales_completed_date", models.DateField(blank=True, null=True)),
                ("programming_completed_date", models.DateField(blank=True, null=True)),
                ("nest_completed_date", models.DateField(blank=True, null=True)),
                ("edge_completed_date", models.DateField(blank=True, null=True)),
                ("prep_completed_date", models.DateField(blank=True, null=True)),
                ("build_completed_date", models.DateField(blank=True, null=True)),
                ("fittings_completed_date", models.DateField(blank=True, null=True)),
                ("wrapping_completed_date", models.DateField(blank=True, null=True)),
                ("quality_completed_date", models.DateField(blank=True, null=True)),
                ("estimated_nest_sheets", models.FloatField(default=0)),
                ("estimated_build_cabs", models.IntegerField(default=0)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="production_stage",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "ordering": ["-order__delivery_date"],
            },
        ),
    ]
