# Generated by Django 5.2.5 on 2025-08-27 09:04

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('location_code', models.CharField(help_text='e.g. PICK-A01-B01-L01', max_length=64)),
                ('qty_on_hand', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'inventory_stockitem',
                'ordering': ['sku'],
            },
        ),
    ]
