# Generated by Django 5.2.5 on 2025-08-27 10:58

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stocktransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'inventory_product',
                'ordering': ['sku'],
            },
        ),
        migrations.RemoveField(
            model_name='stocktransaction',
            name='item',
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='from_location',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='to_location',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='txn_type',
            field=models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT'), ('MOVE', 'MOVE')], max_length=4),
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location_code', models.CharField(help_text='e.g. PICK-A01-B01-L01', max_length=64)),
                ('qty_on_hand', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='inventory.product')),
            ],
            options={
                'db_table': 'inventory_balance',
            },
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='txns', to='inventory.product'),
        ),
        migrations.DeleteModel(
            name='StockItem',
        ),
        migrations.AddConstraint(
            model_name='balance',
            constraint=models.UniqueConstraint(fields=('product', 'location_code'), name='uq_product_location'),
        ),
    ]
