# Generated by Django 5.1.4 on 2025-04-22 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="customer",
            name="postcode",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
