# Generated by Django 5.2 on 2025-06-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='build_kpi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_id', models.CharField(max_length=100, unique=True)),
                ('build_time', models.FloatField()),
                ('build_quality', models.FloatField()),
                ('build_cost', models.FloatField()),
            ],
        ),
    ]
