# Generated by Django 5.2 on 2025-05-09 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('product_name', models.CharField(max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('Board', 'Board'), ('Edge_Banding', 'Edge_Banding'), ('Cabinet', 'Cabinet'), ('Hardware', 'Hardware'), ('Miscellaneous', 'Miscellaneous'), ('Door', 'Door'), ('Pull_Out', 'Pull_Out')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('supplier_id', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('supplier_name', models.CharField(max_length=100)),
                ('contact_person', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('transaction_id', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('transaction_type', models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT')], max_length=10)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryTable',
            fields=[
                ('inventory_id', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('quantity', models.IntegerField(default=0)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('last_updated', models.DateField(auto_now=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.suppliers')),
            ],
        ),
    ]
