# Generated by Django 5.2 on 2025-04-30 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('BOARD', 'Board'), ('EDGE', 'Edge Banding'), ('CABINET', 'Cabinet'), ('STOCK', 'General Stock')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('width', models.PositiveIntegerField(blank=True, help_text='Width in mm', null=True)),
                ('length', models.PositiveIntegerField(blank=True, help_text='Length in mm', null=True)),
                ('height', models.PositiveIntegerField(blank=True, help_text='Height or Depth in mm', null=True)),
                ('thickness', models.DecimalField(blank=True, decimal_places=2, help_text='Thickness in mm', max_digits=5, null=True)),
                ('color', models.CharField(blank=True, max_length=100)),
                ('unit', models.CharField(default='PCS', max_length=10)),
                ('reorder_level', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('barcode_value', models.CharField(blank=True, max_length=50, unique=True)),
            ],
            options={
                'ordering': ['type', 'code'],
            },
        ),
    ]
