# Generated by Django 5.2 on 2025-05-02 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='depth',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
