# Generated by Django 5.2 on 2025-04-30 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_movement'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='barcode_image',
            field=models.ImageField(blank=True, null=True, upload_to='barcodes/'),
        ),
    ]
