# Generated by Django 5.2 on 2025-05-02 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_boardpiece'),
        ('orders', '0002_alter_order_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.PositiveIntegerField()),
                ('width', models.PositiveIntegerField()),
                ('thickness', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_offcut', models.BooleanField(default=True)),
                ('barcode_value', models.CharField(blank=True, max_length=50, unique=True)),
                ('barcode_image', models.ImageField(blank=True, null=True, upload_to='barcodes/boardstock/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('allocated_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocated_stock', to='orders.order')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.location')),
                ('parent_board', models.ForeignKey(limit_choices_to={'type': 'BOARD'}, on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='inventory.item')),
            ],
        ),
        migrations.DeleteModel(
            name='BoardPiece',
        ),
    ]
