# Generated by Django 5.2 on 2025-06-30 14:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='send_to_production',
            field=models.BooleanField(default=False, help_text='Tick to generate a production order.'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, help_text='Expected delivery or collection date', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NO_PAPERWORK', 'No Paperwork'), ('AWAITING_DEPOSIT', 'Awaiting Deposit'), ('IN_PRODUCTION', 'In Production'), ('READY_FOR_DELIVERY', 'Ready for Delivery'), ('DELIVERED', 'Delivered'), ('ON_HOLD', 'On Hold'), ('CANCELLED', 'Cancelled')], db_index=True, default='NO_PAPERWORK', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderattachment',
            name='file',
            field=models.FileField(upload_to='order_attachments/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'png'])]),
        ),
    ]
